// Jenkinsfile

import org.company.jsl.BuildTool
pipeline {
    agent none
    stages {
        stage('Build Setup') {
            steps {
                echo 'Hello, Maven'
                buildTool = new BuildTool(
                    builder        : "Docker",
                    job            : this,
                    dockerRegistry : "172.17.0.1:5050",
                    imageName      : "myimage",
                    imageVersion   : "1.0",
                ).returnBuildTool()
            }
        }
        stage("Notification") {
            steps {
                emailNotification("Success")
            }
        }
    }
}